server:
  udp:
    port: 80
  http:
    port: 80
  mqtt:
    port: 1883
handler:
  sls:
    endpoint: cn-qingdao.log.aliyuncs.com
    projectName: docker-alpha
    logStoreName: go-echo-server
