version: '3'
services:
  echo-server:
    build: .
    environment:
      ALY_APIOPTIONS_ACCESSKEYID: '***'
      ALY_APIOPTIONS_SECRETACCESSKEY: '***'
    ports:
      - 80:80
      - 90:90/udp
