version: '3'
services:
  echo-server:
    build: .
    environment:
      SERVER_UDP_PORT: 80
      SERVER_HTTP_PORT: 80
      GIN_MODE: release
      HANDLER_SLS_ACCESSKEYID: <required>
      HANDLER_SLS_ACCESSKEYSECRET: <required>
      HANDLER_SLS_ENDPOINT: cn-qingdao.log.aliyuncs.com
      HANDLER_SLS_PROJECTNAME: docker-alpha
      HANDLER_SLS_LOGSTORENAME:  go-echo-server
    ports:
      - 80:80
      - 80:80/udp
